### ISSUE TITLE
[Data Request]

### ISSUE THREAD

**Issue by denzalo** [tanho63/dynastyprocess#41]
**Describe the data you'd like to have**
I'm looking for historical ECR or ADP values. I know how to find the current year's, but is there a way to get last year? Or the year before? Do you keep that kind of archive and if so how far back does it go?

A snapshot at some point before the start of the season would be fine.

Thanks!

**Comment by tanho63** [comment]
Try files/db_fpecr - specifically: https://github.com/dynastyprocess/data/blob/master/files/db_fpecr.csv.gz or the rds/parquet equivalents
