### ISSUE TITLE
[Data Bug] Weekly playerids failing

### ISSUE THREAD

**Issue by b1ak3n** [tanho63/dynastyprocess#43]
**Describe the data bug**
Weekly job for updating playerids is failing. Looks to not have successfully completed since last month. The effect is that some players are associated with the wrong team.

** Which file is having trouble?**
Which file?
[db_playerids.csv](https://github.com/dynastyprocess/data/blob/master/files/db_playerids.csv)

**Expected data**
What should this look like?
`db_playerids.csv` updates weekly and gets accurate team info linked for all players.

**Comment by tanho63** [comment]
😬 ope, I hadn't noticed! Thanks for reporting, I'll try to have a look this weekend

**Comment by tanho63** [comment]
A solid month later, have sorted out the root issue (nflverse rosters failing) and so this should now be working again!
