### ISSUE TITLE
[Data Bug] db_playerids.csv 503 error

### ISSUE THREAD

**Issue by kingla6** [tanho63/dynastyprocess#49]
**Describe the data bug**
This code chunk:
```
ffscrapr::dp_playerids()
```

Returns the following:
```
Request failed [503]. Retrying in 1.3 seconds...
Request failed [503]. Retrying in 1.7 seconds...
Error: GitHub request failed with error: <503> 

while calling <https://github.com/DynastyProcess/data/raw/master/files/db_playerids.csv>
```

**Which file is having trouble?**
Which file?
db_playerids.csv

**Expected data**
What should this look like?
This should return the csv as a dataframe.

**Comment by kingla6** [comment]
This is also an issue when trying to access the file via the GitHub UI

[db_playerids.csv](https://github.com/dynastyprocess/data/files/12518839/db_playerids.csv)

**Comment by tanho63** [comment]
Hmm. HTTP 500-series errors tend to indicate a server side issue. Try it again in a little while, perhaps?

**Comment by kingla6** [comment]
Yep, it works now! Any idea what the server issue may have been?

**Comment by tanho63** [comment]
Absolutely not a clue 😅 it would be a GitHub-wide problem
