### ISSUE TITLE
anthony richardson (IND QB) ESPN ID

### ISSUE THREAD

**Issue by izzy714** [tanho63/dynastyprocess#58]
**Is your data request related to a problem? Please describe.**
Just looking to get the ESPN for Anthony Richardson in dp_playerids(). There could be more along the way but this is the first that i've noticed. If there is a better way to make these requests please let me know. 

**Describe the data you'd like to have**
For more ESPN player IDs to b filled in

**Where can we source this data?**
dp_playerids()

**Additional context**
N/A

**Comment by mcarman8** [comment]
@izzy714 This should be resolved from an update with pull requests #56 and #57. Can you confirm?
