### ISSUE TITLE
[Data Bug] CBS Ids truncated for 2024 Players

### ISSUE THREAD

**Issue by jplata** [tanho63/dynastyprocess#64]
**Describe the data bug**
It would appear cbs_id column for many (all?) new players for 2024 are missing the final digit. 

**Which file is having trouble?**
db_playerids.csv

**Expected data**
Example: 
- Jonathon Brooks cbs_id in file: 2673070
- Jonathon Brooks _actual_ cbs_id: 26730706

- Malik Nabers cbs_id in file: 2669776
- Malik Nabers _actual_ cbs_id: 26697761

**Comment by tanho63** [comment]
Hm, this is strange. I think we get these IDs from the MFL API. Do you have a list of all the ones that are wrong ?

**Comment by jplata** [comment]
I don't have a full list, I was pulling in 2024 Draft Data for a league, and noticed it was not matching on the 2024 rookies - so my assumption is any new players added in 2024 could be wrong.

**Comment by jplata** [comment]
Should we open a ticket w/ MFL to see if they can resolve the CBS player ids? Or any other known solutions?

**Comment by tanho63** [comment]
Yeah, it could be worth trying with MFL support, would you like to give that a go?

**Comment by jplata** [comment]
@tanho63 This appears to be resolved now!

**Comment by tanho63** [comment]
Awesome!
