### ISSUE TITLE
Nfl player missing

### ISSUE THREAD

**Issue by Kbs42** [tanho63/dynastyprocess#65]
Jalen Coker is not in database  he is WR2 for the Carolina panthers

**Comment by tanho63** [comment]
which file?

**Comment by Kbs42** [comment]
Jalen Coker

**Comment by tanho63** [comment]
That’s not a file, that’s a player, and the player is in the db_playerids.csv file.

**Comment by Kbs42** [comment]
Ok, thanks for the clarification. He just doesn't pop up in the app and was
trying to get it fixed
